[package]
name = "hachi"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = "2.0.0-rc.10"
tetris = { git = "https://github.com/citrus610/sunbeam", rev = "bcf64cd" }
ndarray = "0.15"
anyhow = "1.0"